POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{
	"id": 4,
	"titulo": "Aprende Node.js",
	"lenguaje": "javascript",
	"visitas": 45676,
	"nivel": "basico"
}

###
PUT http://localhost:3000/api/cursos/programacion/7 HTTP/1.1
Content-Type: application/json

{
  "id": 2,
	"titulo": "Python Super Avanzado",
	"lenguaje": "python",
	"visitas": 85963,
	"nivel": "avanzado"
}

###
PATCH http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
	"visitas": 175963
}

###
DELETE http://localhost:3000/api/cursos/programacion/7 HTTP/1.1

